# -*- coding: utf-8 -*-
"""test_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ilzV0ZasdFeHqCScJRRcxY3HXQpgVr4e
"""

import torch
import torch.nn as nn
from torchvision.models import vgg16

# ---------------------------
# small helper conv block: Conv2d -> BN -> ReLU
# ---------------------------
def conv_bn_relu(in_c, out_c, kernel_size=3, stride=1, padding=1):
    return nn.Sequential(
        nn.Conv2d(in_c, out_c, kernel_size=kernel_size, stride=stride, padding=padding, bias=False),
        nn.BatchNorm2d(out_c),
        nn.ReLU(inplace=True)
    )


# ---------------------------
# Pretrained VGG16 feature extractor (up to pool3)
# ---------------------------
class VGG16Blocks(nn.Module):
    def __init__(self, pretrained=True, to_pool3=True):
        """
        to_pool3=True -> use features up to pool3 (more semantic features): output channels = 256, spatial 28x28
        """
        super().__init__()
        vgg = vgg16(weights='IMAGENET1K_V1' if pretrained else None)
        if to_pool3:
            # children() slice to include layers up to pool3 (index 17)
            self.features = nn.Sequential(*list(vgg.features.children())[:17])  # conv.. -> pool3
            self.out_channels = 256
        else:
            # keep original behavior (pool2)
            self.features = nn.Sequential(*list(vgg.features.children())[:10])  # conv.. -> pool2
            self.out_channels = 128

    def forward(self, x):
        return self.features(x)  # [B, out_channels, H, W]


# ---------------------------
# Inception v7 block (improved: BN + ReLU in all convs)
# ---------------------------
class InceptionV7(nn.Module):
    def __init__(self, in_channels=256, out_channels=512, branch_channels=128, dropout=0.0):
        """
        in_channels: channels from previous layer (e.g., 256 if using pool3)
        out_channels: final projected channels (e.g., 512)
        branch_channels: intermediate channels per branch (128 typical)
        """
        super().__init__()
        b = branch_channels

        # Branch 1: 1x1
        self.branch1 = conv_bn_relu(in_channels, b, kernel_size=1, stride=1, padding=0)

        # Branch 2: 1x1 -> (3x1) -> (1x3)
        self.branch2 = nn.Sequential(
            conv_bn_relu(in_channels, b, kernel_size=1, stride=1, padding=0),
            conv_bn_relu(b, b, kernel_size=(3, 1), stride=1, padding=(1, 0)),
            conv_bn_relu(b, b, kernel_size=(1, 3), stride=1, padding=(0, 1)),
        )

        # Branch 3: 1x1 -> (3x1+1x3) -> (3x1+1x3)
        self.branch3 = nn.Sequential(
            conv_bn_relu(in_channels, b, kernel_size=1, stride=1, padding=0),
            conv_bn_relu(b, b, kernel_size=(3, 1), stride=1, padding=(1, 0)),
            conv_bn_relu(b, b, kernel_size=(1, 3), stride=1, padding=(0, 1)),
            conv_bn_relu(b, b, kernel_size=(3, 1), stride=1, padding=(1, 0)),
            conv_bn_relu(b, b, kernel_size=(1, 3), stride=1, padding=(0, 1)),
        )

        # Branch 4: MaxPool 3x3 (stride 1 pad1) -> 1x1 conv
        self.branch4 = nn.Sequential(
            nn.MaxPool2d(3, stride=1, padding=1),
            conv_bn_relu(in_channels, b, kernel_size=1, stride=1, padding=0)
        )

        # Project concatenated branches to out_channels
        self.proj = conv_bn_relu(b * 4, out_channels, kernel_size=1, stride=1, padding=0)

        # Optional dropout on output of inception
        self.dropout = nn.Dropout2d(p=dropout) if dropout > 0 else nn.Identity()

    def forward(self, x):
        x1 = self.branch1(x)
        x2 = self.branch2(x)
        x3 = self.branch3(x)
        x4 = self.branch4(x)
        out = torch.cat([x1, x2, x3, x4], dim=1)
        out = self.proj(out)
        out = self.dropout(out)
        return out  # [B, out_channels, H, W]


# ---------------------------
# Reduce spatial dims to reduce token count (Conv stride)
# ---------------------------
class SpatialReducer(nn.Module):
    def __init__(self, in_channels=512, out_channels=512, stride=4):
        """
        Reduce HxW by stride (e.g., 28->7 when stride=4).
        """
        super().__init__()
        self.reduce = conv_bn_relu(in_channels, out_channels, kernel_size=3, stride=stride, padding=1)

    def forward(self, x):
        return self.reduce(x)  # [B, out_channels, H//stride, W//stride]


# ---------------------------
# Patch Encoder + Positional Embedding
# ---------------------------
class PatchEncoder(nn.Module):
    def __init__(self, in_c=512, emb_dim=32, grid_size=(7, 7)):
        super().__init__()
        self.in_c = in_c
        self.emb_dim = emb_dim
        self.grid_h, self.grid_w = grid_size
        self.num_patches = self.grid_h * self.grid_w
        self.proj = nn.Linear(in_c, emb_dim)
        # learnable pos emb
        self.pos_embed = nn.Parameter(torch.randn(1, self.num_patches, emb_dim) * 0.02)

    def forward(self, x):
        # x: [B, C, H, W] where H=W=grid_size
        B, C, H, W = x.shape
        assert H == self.grid_h and W == self.grid_w, f"Expected grid {self.grid_h}x{self.grid_w}, got {H}x{W}"
        x = x.permute(0, 2, 3, 1).reshape(B, H * W, C)  # [B, N, C]
        x = self.proj(x)  # [B, N, emb_dim]
        x = x + self.pos_embed  # add positional embedding
        return x  # [B, N, emb_dim]


# ---------------------------
# ViT Encoder (configurable)
# ---------------------------
class ViTEncoder(nn.Module):
    def __init__(self, emb_dim=32, depth=6, heads=4, mlp_dim=128, dropout=0.1):
        super().__init__()
        # ensure emb_dim divisible by heads
        assert emb_dim % heads == 0, "emb_dim must be divisible by heads"
        self.layers = nn.ModuleList([
            nn.TransformerEncoderLayer(
                d_model=emb_dim,
                nhead=heads,
                dim_feedforward=mlp_dim,
                dropout=dropout,
                batch_first=True,
                norm_first=True
            ) for _ in range(depth)
        ])
        self.final_norm = nn.LayerNorm(emb_dim)

    def forward(self, x):
        # x: [B, N, emb_dim]
        for layer in self.layers:
            x = layer(x)
        x = self.final_norm(x)
        return x  # [B, N, emb_dim]


# ---------------------------
# Attention Pooling (weighted sum of tokens)
# ---------------------------
class AttentionPool(nn.Module):
    def __init__(self, emb_dim):
        super().__init__()
        self.attn = nn.Linear(emb_dim, 1)

    def forward(self, x):
        # x: [B, N, emb_dim]
        scores = self.attn(x)         # [B, N, 1]
        weights = torch.softmax(scores, dim=1)  # [B, N, 1]
        pooled = (x * weights).sum(dim=1)  # [B, emb_dim]
        return pooled


# ---------------------------
# Full PlantXViT v2 (optimized)
# ---------------------------
class PlantXViT_v2(nn.Module):
    def __init__(
        self,
        num_classes=8,
        emb_dim=32,
        pretrained_vgg=True,
        use_pool3=True,
        inception_out_channels=512,
        reducer_stride=4,
        vit_depth=6,
        vit_heads=4,
        vit_mlp=128,
        vit_dropout=0.1,
        classifier_dropout=0.3
    ):
        super().__init__()

        # 1) VGG blocks (pretrained). By default use up to pool3 for richer features
        self.vgg = VGG16Blocks(pretrained=pretrained_vgg, to_pool3=use_pool3)
        vgg_out_c = self.vgg.out_channels  # 256 if pool3, else 128

        # 2) Inception block (take vgg_out_c -> inception_out_channels)
        self.inception = InceptionV7(in_channels=vgg_out_c, out_channels=inception_out_channels, branch_channels=128, dropout=0.0)

        # 3) spatial reducer to shrink patch grid (e.g., 28->7 with stride=4)
        self.reducer = SpatialReducer(in_channels=inception_out_channels, out_channels=inception_out_channels, stride=reducer_stride)
        # calculate grid size after reduction: if input 28 and stride 4 -> 7
        # We'll set grid_size = (H_after, W_after)
        # For standard 224 input and pool3 -> 28 -> stride4 -> 7
        grid_size = (7, 7)

        # 4) Patch encoder + positional embeddings
        self.patch_encoder = PatchEncoder(in_c=inception_out_channels, emb_dim=emb_dim, grid_size=grid_size)

        # 5) ViT encoder
        self.transformer = ViTEncoder(emb_dim=emb_dim, depth=vit_depth, heads=vit_heads, mlp_dim=vit_mlp, dropout=vit_dropout)

        # 6) Pooling (attention) + classifier head
        self.attn_pool = AttentionPool(emb_dim)
        self.norm = nn.LayerNorm(emb_dim)
        self.dropout = nn.Dropout(classifier_dropout)
        self.classifier = nn.Linear(emb_dim, num_classes)

    def forward(self, x):
        # x: [B, 3, 224, 224]
        x = self.vgg(x)              # [B, vgg_out_c, Hv, Wv] e.g., [B,256,28,28]
        x = self.inception(x)        # [B, inception_out, Hv, Wv] e.g., [B,512,28,28]
        x = self.reducer(x)          # [B, inception_out, Hr, Wr] e.g., [B,512,7,7]
        x = self.patch_encoder(x)    # [B, N=49, emb_dim]
        x = self.transformer(x)      # [B, N, emb_dim]
        x = self.attn_pool(x)        # [B, emb_dim]
        x = self.norm(x)
        x = self.dropout(x)
        x = self.classifier(x)       # [B, num_classes]
        return x


# ---------------------------
# Quick test
# ---------------------------
if __name__ == "__main__":
    model = PlantXViT_v2(
        num_classes=8,
        emb_dim=32,
        pretrained_vgg=True,
        use_pool3=True,
        inception_out_channels=512,
        reducer_stride=4,
        vit_depth=6,
        vit_heads=4,
        vit_mlp=128,
        vit_dropout=0.1,
        classifier_dropout=0.3
    )
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model = model.to(device)
    x = torch.randn(2, 3, 224, 224).to(device)
    y = model(x)
    print("Output shape:", y.shape)
    print("Total parameters:", sum(p.numel() for p in model.parameters()))

from google.colab import drive
drive.mount('/content/drive')

import torch
from torchvision import transforms
from PIL import Image

# --- Load model ---
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = PlantXViT_v2(num_classes=8).to(device)
checkpoint = torch.load(
    "/content/drive/MyDrive/PBL6_checkpoints_l7/PlantXViT_best.pth",
    map_location=device,
    weights_only=False
)
model.load_state_dict(checkpoint["model_state"])

model.eval()

# --- Preprocess ảnh ---
transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406],
                         std=[0.229, 0.224, 0.225])
])

# --- Dự đoán ---
def predict_image(img_path, class_names):
    img = Image.open(img_path).convert("RGB")
    x = transform(img).unsqueeze(0).to(device)
    with torch.no_grad():
        logits = model(x)
        probs = torch.softmax(logits, dim=1)[0]
        pred = probs.argmax().item()
    print(f"Predicted: {class_names[pred]} ({probs[pred]:.3f})")
    return pred, probs

class_names = [
    'bacterial_leaf_blight',
    'bacterial_panicle_blight',
    'blast',
    'brown_spot',
    'leaf_roller',
    'normal',
    'stem_borer',
    'tungro'
]

predict_image("/content/drive/MyDrive/leaf_roller.jpg", class_names)